[package]
name = "rcas"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "7.1.3"
num-bigint = "0.4"
num-rational = { version = "0.4", features = ["num-bigint"] }
num-traits = "0.2"
thiserror = "1.0"
